#!/usr/bin/python

import argparse
from common import get_values, values2numbers


def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("-f", "--format", action="store_true")
    parser.add_argument('values', nargs="*")
    args = parser.parse_args()
    return args

args = get_args()
values = get_values(args)
numbers = values2numbers(values)

if "year" in args.format:

