#!/usr/bin/python
import random
# from common import get_args, get_values, values2numbers


# args = get_args()
# values = get_values(args)
# numbers = values2numbers(values)
print int(random.random() * 1001)
