#!/usr/bin/python
import sys

def sqrt(x):
    return float(x)**0.5

try:
    print sqrt(sys.argv[1])
except IndexError:
    all_numbers = sys.stdin.read().split()
    for number in all_numbers:
        try:
	    print sqrt(number)
	except ValueError:
            print "negative number {} not allowed".format(number)
